name: Empty

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [chameleon-event]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout external code
        uses: actions/checkout@v4
        with:
          repository: 'yusitnikov/test-github-actions'
          token: '${{ secrets.TEST_ACTIONS_PAT }}'
          ref: main
          path: external
          fetch-depth: 0
          sparse-checkout: |
            c.json
          sparse-checkout-cone-mode: false

      - name: Update the code
        id: update
        run: |
          mv external/c.json ./c.json
          rm -rf external

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: 'auto-pr'
          delete-branch: true
          add-paths: c.json
          title: 'Update from external repo'
          body: ''
          commit-message: 'ci: update from external repo'
