name: Empty

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [chameleon-event]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout external code
        uses: actions/checkout@v4
        with:
          repository: 'yusitnikov/test-github-actions'
          token: '${{ secrets.TEST_ACTIONS_PAT }}'
          ref: main
          path: external
          fetch-depth: 0
          sparse-checkout: |
            c.json
          sparse-checkout-cone-mode: false

      - name: Show my code
        run: ls -al .

      - name: Show external code
        run: ls -al external
